name: image_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  freezed: ^2.5.2
  http: ^1.2.2
  riverpod: ^2.6.1
  dio: ^5.7.0
  retrofit: ^4.4.1
  retrofit_generator: '>=8.0.0 <10.0.0'
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.6.1
  mockito: ^5.4.4
  cached_network_image: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true
